message = """
CQ CQ CQ DE DDH47 DDH9 DDH8
FREQUENCIES   147.3 KHZ   11039 KHZ   14467.3 KHZ
RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRY
ZCZC 726    
FEMM54 EDZW 280600

MITTELFRIST - SEEWETTERBERICHT FUER DAS MITTELMEER
HERAUSGEGEBEN VOM SEEWETTERDIENST HAMBURG
AM 28.07.2010 11 UTC:

WETTERLAGE:
AM DONNERSTAG AZORENHOCHKEIL 1015 SCHWEIZ - PYRENAEEN -
NORDWESTTEIL SPANIEN BIS MADEIRA, IM SUEDOSTTEIL VERSTAERKEND, AM
SONNTAG ALS KEIL 1015 ADRIA - GROSSE SYRTE - TUNESIEN -
SUEDSPANIEN - NORDSPANIEN - NORDWESTTEIL SPANIDN BIS MADEIRA.
HITZETIEF 1010 SPANIEN, WENIG AENDERND, AB SONNTAG ABSCHWAECHEND.
AM DONNERSTAG TIEF 1010 LIGURISCHES MEER, LANGSAM OSTZIEHEND,
AM SONNABEND 1011 ADRIA, ABSCHWAECHEND, OSTZIEHEND. AM
DONNERSTAG TIEF 1008 TUERKEI, WENIG AENDERND, AB SONNABEND
ABSCHWAECHEND. SONST MEIST GERINGE LUFTDRUCKGEGENSAETZE.


HINWEIS ZU MODELLVORHERSAGEN:
---

VORHERSAGEN VON MI 28.07.2010 00 UTC:
WINDSTAERKE BEAUFORT, WELLENHOEHE METER

GOLFE-LION (42.2N  4.5E) WT: 20 C
DO 29. 00Z: W        4         1  M //
DO 29. 12Z: NW     4-5         1  M //
FR 30. 00Z: NW-N     5   6-7  1.5 M //
FR 30. 12Z: NW-N     5     7  1.5 M //
SA 31. 00Z: NW-N     3        0.5 M //
SA 31. 12Z: NW-N   2-3        0.5 M //
SO  1. 00Z: S      2-3         0  M //
SO  1. 12Z: S        3        0.5 M //
MO  2. 00Z: S-SW     3        0.5 M //
MO  2. 12Z: NW-N   2-3         0  M //


CQ CQ CQ DE DDH47 DDH9 DDH8
FREQUENCIES   147.3 KHZ   11039 KHZ   14467.3 KHZ
RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRY
ZCZC 727    
WODL45 EDZW 281800
STRONGWIND GALE STORMWARNINGS FOR SEA AREAS:
GERMAN BIGHT, WESTERN AND SOUTHERN BALTIC.

GERMAN BIGHT:
NO WARNING.

WESTERN BALTIC:
NO WARNING.

SOUTHERN BALTIC:
NO WARNING.

COASTAL AREA WARNINGS:
STARKWIND, STURMWARNUNGEN FUER DEUTSCHE KUESTEN.

NR. 311
WIND - WARNUNG DES SEEWETTERDIENSTES HAMBURG
FUER DIE DEUTSCHE NORDSEEKUESTE
HERAUSGEGEBEN AM 28.07.2010 UM 17:25 UHR GZ.
ELBEMUENDUNG: NORDWEST 5 BIS 6 DABEI BOEEN VON 7 BEAUFORT.
SEEGEBIET HELGOLAND: NORDWEST 5 BIS 6 DABEI BOEEN VON 7 BEAUFORT.
NORDFRIESISCHE KUESTE: NORDWEST 5 BIS 6 DABEI BOEEN VON 7 BEAUFORT.

NR. 283
WIND - WARNUNG DES SEEWETTERDIENSTES HAMBURG
FUER DIE DEUTSCHE OSTSEEKUESTE
HERAUSGEGEBEN AM 28.07.2010 UM 19:15 UHR GZ.
FLENSBURG BIS FEHMARN WEST BIS NORDWEST 5 BIS 6 DABEI BOEEN VON
7 BEAUFORT.
OESTLICH FEHMARN BIS RUEGEN WEST BIS NORDWEST 5 BIS 6 DABEI BOEEN
VON 7 BEAUFORT.
OESTLICH RUEGEN WEST BIS NORDWEST 5 BIS 6 DABEI BOEEN VON 7
BEAUFORT.

SEEWETTERDIENST HAMBURG

=

CQ CQ CQ DE DDH47 DDH9 DDH8
FREQUENCIES   147.3 KHZ   11039 KHZ   14467.3 KHZ
RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRY
ZCZC 728    
FQEN50 EDZW 281700


SEEWETTERBERICHT FUER NORD- UND OSTSEE
HERAUSGEGEBEN VOM SEEWETTERDIENST HAMBURG
28.07.2010, 20 UHR:

IN DEN NAECHSTEN 12 STUNDEN IST IN FOLGENDEN
VORHERSAGEGEBIETEN MIT STARKWIND ODER STURM ZU RECHNEN:
DEUTSCHE BUCHT
FISCHER
UTSIRA
WESTLICHE OSTSEE
SUEDLICHE OSTSEE
BODDENGEWAESSER OST
SUEDOESTLICHE OSTSEE
ZENTRALE OSTSEE
NOERDLICHE OSTSEE
ENGL. KANAL OSTTEIL

WETTERLAGE:
TIEF 1003 LITAUEN, VERTIEFEND UND NORDNORDWESTZIEHEND,
DONNERSTAG ABEND 998 SUEDSCHWEDEN. TIEF 1012 DICHT SUEDWESTLICH
VON ISLAND, AUFFUELLEND. TIEF 1007 SUEDNORWEGEN, WENIG AENDERND.
AUSLAEUFER 1010 SKAGERRAK, 1010 WESTLICHE OSTSEE, 1011 SACHSEN
1015 WESTDEUTSCHLAND, LANGSAM SUEDOSTSCHWENKEND. HOCH 1028
NORDOESTLICH DER AZOREN MIT KEIL 1020 INNERE BISKAYA, WENIG
AENDERND. TIEF 1013 SUEDLICHES PORTUGAL, ETWAS NORDOSTZIEHEND.
UMFANGREICHES STURMTIEF 999 LABRADORSEE, NORDOSTZIEHEND,
DONNERSTAG FRUEH 1000 SUEDWESTLICH VON ISLAND.

VORHERSAGEN BIS 29.07.2010, 12 UHR:
ENGL. KANAL WESTTEIL:
WEST BIS NORDWEST 3 BIS 4, SCHAUERBOEEN, SEE 1 BIS 1,5 METER.

ENGL. KANAL OSTTEIL:
NORDWEST UM 5, SCHAUERBOEEN, STRICHWEISE DIESIG, SEE 0,5 BIS
1,5 METER."""